version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=wisely_test
    ports:
      - "5432:5432"
  adminer:
    image: wodby/adminer:4.7
    ports:
      - "9000:9000"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=wisely_test
    depends_on:
      - postgres
